In [2]:
! pip install numpy

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b=np.array([[9,8,7],[6,5,4]])
b

array([[9, 8, 7],
       [6, 5, 4]])

In [6]:
#get dimensions
b.ndim

2

In [9]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
#get type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

In [11]:
#get size
a.itemsize

4

In [12]:
#number of elements
b.size

6

In [13]:
#get total size
a.size*a.itemsize

12

In [14]:
a.nbytes

12

## Accessing/Changing specific elements,rows,columns,etc

In [15]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [16]:
# get a specific elemets
a[1,-1]

14

In [17]:
a[1,6]

14

In [18]:
#get a row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
#get a column
a[:,2]

array([ 3, 10])

In [20]:
a[0,1:6]

array([2, 3, 4, 5, 6])

In [21]:
#changing elements in a column
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 13, 14]])

## 3d example


In [22]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
#get specific element
b[0,1,1]

4

In [24]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
#you can replace the elements too

## initializing different types of arrays

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [29]:
#any other number
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [30]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
#random decimal numbers
np.random.rand(4,3)

array([[0.83591585, 0.6527761 , 0.22905671],
       [0.32868234, 0.792011  , 0.93562027],
       [0.40164065, 0.99803421, 0.08432499],
       [0.18682251, 0.34508185, 0.48213167]])

In [32]:
np.random.random_sample(a.shape)

array([[0.05292959, 0.44772954, 0.53406732, 0.29694593, 0.3044147 ,
        0.99599624, 0.74473392],
       [0.09064293, 0.93073796, 0.91605634, 0.92383083, 0.75218425,
        0.40685685, 0.08486144]])

In [42]:
np.random.randint(1,14,size=(3,3))

array([[12,  4, 10],
       [ 7, 11, 12],
       [11,  9, 12]])

## identity matrix

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
#repeat array
arr=np.array([[1],[2],[3]])
r1=np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [50]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [51]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## be careful when copying arrays

In [53]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
a

array([1, 2, 3])

## mathematics

In [61]:
a=np.array([1,2,3,4])
a-2

array([-1,  0,  1,  2])

In [55]:
a+=4
a

array([5, 6, 7, 8])

In [56]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [62]:
b=np.array([1,2,3,4])
a*b

array([ 1,  4,  9, 16])

## linear algebra

In [65]:
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [63]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [4]:
#for inverse
d=np.array([[1,2],[3,4]])
np.linalg.inv(d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## statistics

In [6]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.max(stats)

6

In [8]:
np.max(stats,axis=1)

array([3, 6])

In [9]:
np.sum(stats)

21

In [10]:
np.sum(stats,axis=1)

array([ 6, 15])

## reorgranizing arrays

In [14]:
before=np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
after=before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [16]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## miscallenious

In [21]:
filedata=np.genfromtxt('NumPy-master/data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## boolean masking and advanced indexing

In [22]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [23]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [24]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [25]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [26]:
final=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

In [27]:
final[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [28]:
final[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [37]:
final[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])